name: Check for cache hit using API
inputs:
  key:
    description: An explicit key or prefix for identifying the cache
    required: false
    default: ''
  ref:
    description: The ref to use when checking the API
    required: true
  repo-token:
    description: Token to use to authorize actions API access. Typically the GITHUB_TOKEN secret, with actions:read access
    required: false
outputs:
  cache-hit:
    description: A boolean value to indicate a match was found for the key or prefix.
    value: ${{ steps.get-api.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Check for cache hit using API
      id: get-api
      shell: bash
      env:
        REPO_TOKEN: ${{ inputs.repo-token }}
      run: |
        : Checking the API for cache entries on '${{ inputs.ref }}' with key '${{ inputs.key }}'

        if [ ! -z $REPO_TOKEN ]; then export GH_TOKEN=$REPO_TOKEN; fi

        cache_hit=$(gh api \
          --method GET \
          -H 'Accept: application/vnd.github+json' \
          -H 'X-GitHub-Api-Version: 2022-11-28' \
          -f 'key=${{ inputs.key }}' \
          -f 'ref=${{ inputs.ref }}' \
          /repos/${{ github.repository }}/actions/caches \
            | jq '.total_count != 0')

        echo "cache-hit=$cache_hit" >> $GITHUB_OUTPUT
